version: '3.8'				
services:					
  api:
    build:
      context: .
    ports:
      - 8080:8080
    env_file:
      - ./.env
    # volumes:
      # - node_modules:/usr/src/app/node_modules
      # - logs:/usr/src/app/logs
      # - docs:/usr/src/app/docs
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
#  node_modules:
#  logs:
#  docs: